// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Cu62vpTv6cUkOK3m6wpXTL5kcX_4toI',
    appId: '1:1040493098798:web:10b5d33935ce3947a5acbf',
    messagingSenderId: '1040493098798',
    projectId: 'zzaala',
    authDomain: 'zzaala.firebaseapp.com',
    storageBucket: 'zzaala.firebasestorage.app',
    measurementId: 'G-NM54YNV3BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDdJfxAixHe6sbcFUzPsJpBBmhgk5FBk',
    appId: '1:1040493098798:android:accda5ca1db6f7eaa5acbf',
    messagingSenderId: '1040493098798',
    projectId: 'zzaala',
    storageBucket: 'zzaala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3xPV4zutUMDingJKXXbpPV0T5SACFfQ',
    appId: '1:1040493098798:ios:8a7132b5e5d73f5ca5acbf',
    messagingSenderId: '1040493098798',
    projectId: 'zzaala',
    storageBucket: 'zzaala.firebasestorage.app',
    iosBundleId: 'com.infoholiks.chezagames',
  );
}
